# Multi-lingual Chunking Configuration
# Supports Chinese, English, and French text

[chunking]
# Text splitting method: "sentence" or "newline"
# - "sentence": Use robust sentence splitter with punctuation detection
# - "newline": Split on newlines (\n) for simpler chunks
splitter_method = "newline"

[sentence_splitter]
# Configuration for sentence-based splitting (when splitter_method = "sentence")

# Universal sentence punctuation
chinese_punctuation = ["。", "！", "？", "......"]  # removed "；"
western_punctuation = [".", "!", "?", "..."]

# Quotation mark pairs: [opening, closing]
# ASCII quotes use same character for open/close (ambiguous)
# Other quotes have distinct open/close characters (unambiguous)
quote_pairs = [
    ["\"", "\""],        # ASCII double quotes (ambiguous)
    ["'", "'"],          # ASCII single quotes (ambiguous)
    ["\u201c", "\u201d"],  # Curved/Chinese double quotes " " (unambiguous)
    ["\u2018", "\u2019"],  # Curved/Chinese single quotes ' ' (unambiguous)
    ["\u300c", "\u300d"],  # Chinese corner brackets 「 」 (unambiguous)
    ["\u300e", "\u300f"],  # Chinese double corner brackets 『 』 (unambiguous)
    ["\u00ab", "\u00bb"]   # French guillemets « » (unambiguous)
]

# English abbreviations that should NOT trigger sentence splits
english_abbreviations = [
    # Titles
    "Mr", "Mrs", "Ms", "Dr", "Prof", "Sr", "Jr",
    # Academic degrees
    "Ph\\.D", "B\\.A", "M\\.A", "B\\.S", "M\\.S", "B\\.Sc", "M\\.Sc",
    # Business
    "Inc", "Ltd", "Corp", "Co", "LLC",
    # Common abbreviations
    "etc", "vs", "i\\.e", "e\\.g", "cf", "ibid",
    # Time
    "a\\.m", "p\\.m", "AM", "PM",
    # Units
    "cm", "km", "kg", "lb", "oz", "ft", "in"
]

# French abbreviations
french_abbreviations = [
    # Titles
    "M", "Mme", "Mlle", "Dr", "Prof",
    # Common
    "c\\.-à-d", "p\\. ex", "cf", "etc"
]

[newline_splitter]
# Configuration for newline-based splitting (when splitter_method = "newline")

# Split mode: "paragraph" or "line"
# - "paragraph": Split on multiple consecutive newlines (paragraph breaks)
# - "line": Split on single newlines (original behavior)
# NOTE: Notion's default is "paragraph", the original doc is always separated by at least 2 newlines
# - if you write in Notion and use ENTER to create a new line, it will be separated by 2 newlines
# - if you use SHIFT + ENTER to create a new line, it will be separated by 1 newline
split_mode = "paragraph"

# Minimum consecutive newlines to consider a paragraph break (default: 2)
# Only used when split_mode = "paragraph"
paragraph_break_threshold = 2

[semantic_merging]
# Similarity threshold for merging adjacent sentences
similarity_threshold = 0.45

# Maximum number of times text units can be merged)
max_merge_distance = 5

# Maximum chunk size in tokens (merging stops when this would be exceeded)
# 
# NOTE: Token counting depends on the tokenizer used:
# - OpenAI tokenizers (tiktoken): Subword-based tokenization
#   * English/French: Common words = 1 token, complex words = 2-4 tokens
#   * Chinese: Characters often 1-2 tokens each, but varies by context
#   * Example: "Hello world" = 2 tokens, "你好世界" = 4 tokens
# - Other tokenizers may count differently (whitespace, character-based, etc.)
# 
# For reference with OpenAI's cl100k_base tokenizer:
# - English: ~1 token per 0.75 words (750 words ≈ 1000 tokens)
# - Chinese: ~1 token per 0.5-1 characters (500-1000 characters ≈ 1000 tokens)
# - Mixed content: Token density varies by language ratio
max_chunk_size = 500

[embeddings]
# Internal configuration (not passed to OpenAI API)
batch_size = 512  # For our internal batching logic
delay_seconds = 0.1  # Rate limiting delay

[embeddings.openai]
# OpenAI API parameters (passed directly to embeddings.create)
model = "text-embedding-3-small"
dimensions = 1536