# Simple evaluation configuration
[collection]
# Notion database IDs to collect from
database_ids = [
    "1519782c4f4a80dc9deff9768446a113"  # 他山之石
]

# Basic settings
output_dir = "data"
min_content_length = 10 